stateDiagram
	[*]-->INITALIZE
	INITALIZE --> CHECK_CHILLER_AVAIL
	CHECK_CHILLER_AVAIL --> CHECK_RESEQUENCE
	CHECK_CHILLER_AVAIL --> WAIT_LOOP
	CHECK_RESEQUENCE --> RUNTIME_RESEQUENCE
	CHECK_RESEQUENCE --> SEQUENCE_RESET
	SEQUENCE_RESET --> SEQUENCE_SCORE
	SEQUENCE_SCORE --> CHILLER_ORDER
	CHILLER_ORDER --> SET_SEQUENCE
	RUNTIME_RESEQUENCE --> SET_SEQUENCE
	SET_SEQUENCE --> WAIT_LOOP
	WAIT_LOOP --> INITALIZE
